Create run_xUnique script directly from setup

diff --git a/xcode-project-setup/setup b/xcode-project-setup/setup
--- a/xcode-project-setup/setup
+++ b/xcode-project-setup/setup
@@ -873,6 +873,27 @@ EOF
 # # # # # # # # # # # # # # # # # # # # #
 
 
+# # # # # # # # # # # # # # # # # # # # #
+# Create run_xUnique script
+cat <<EOF > "scripts/run_xUnique"
+#!/bin/bash
+
+
+if [ -z "$1" ]
+then
+    echo "Error: Need to provide project name as argument"
+    exit 1
+fi
+
+PROJECT_NAME=$1
+
+echo "Running xUnique..."
+bash -l -c "python ./scripts/xUnique.py $PROJECT_NAME.xcodeproj/ > /dev/null"
+EOF
+#
+# # # # # # # # # # # # # # # # # # # # #
+
+
 echo "# # #"
 
 
