Create run_synx script directly from setup

diff --git a/xcode-project-setup/setup b/xcode-project-setup/setup
--- a/xcode-project-setup/setup
+++ b/xcode-project-setup/setup
@@ -874,6 +874,27 @@ EOF
 
 
 # # # # # # # # # # # # # # # # # # # # #
+# Create run_synx script
+cat <<EOF > "scripts/run_synx"
+#!/bin/bash
+
+
+if [ -z "$1" ]
+then
+    echo "Error: Need to provide project name as argument"
+    exit 1
+fi
+
+PROJECT_NAME=$1
+
+echo "Running synx..."
+bash -l -c "synx --prune --quiet $PROJECT_NAME.xcodeproj/"
+EOF
+#
+# # # # # # # # # # # # # # # # # # # # #
+
+
+# # # # # # # # # # # # # # # # # # # # #
 # Create run_xUnique script
 cat <<EOF > "scripts/run_xUnique"
 #!/bin/bash
